from setuptools import setup, find_packages

setup(
    name="complexity",
    version="0.1.0",
    description="Complexity classification system",
    author="Your Name",
    author_email="your.email@example.com",
    python_requires=">=3.10",
    packages=find_packages(where="server/src"),
    package_dir={"": "server/src"},
    install_requires=[
        "datasets",
        "pandas",
        "matplotlib",
        "seaborn",
        "python-dotenv",
        "litellm",
        "requests",
        "markdownify",
        "tenacity>=9.0.0",
        "loguru>=0.7.3",
        "spacy>=3.8.4",
        "python-arango>=8.1.4",
        "deepmerge>=2.0",
        "torch>=2.2.2",
        "transformers>=4.48.1",
        "sentence-transformers>=3.4.0",
        "nltk>=3.9.1",
        "pyperclip>=1.9.0",
        "json-repair>=0.35.0",
        "rapidfuzz>=3.11.0",
    ],
    extras_require={"dev": ["pytest", "ipython", "jupyterlab", "pre-commit>=3.6.0"]},
)
